package com.colak.springjpainheritancetutorial.jpa;

import jakarta.persistence.Column;
import jakarta.persistence.DiscriminatorColumn;
import jakarta.persistence.DiscriminatorType;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Inheritance;
import jakarta.persistence.InheritanceType;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "items")
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)

@Getter
@Setter
public class Item {
    @Id
    // This can not be GenerationType.IDENTITY anymore
    // So id column can not be defined as "generated by default as identity"

    // GenerationType.AUTO makes JPA use a sequence
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "items_seq_generator")
    @SequenceGenerator(name = "items_seq_generator", sequenceName = "items_seq", allocationSize = 1)
    private Long id;

    private String itemName;

}

